### ISSUE TITLE
platform will fail to build with CMake 4

### ISSUE THREAD

**Issue by NHOrus** [Pulse-Eight/platform#52]
CMake 4 raised minimum compatible version to CMake 3.5.
See https://gitlab.kitware.com/cmake/cmake/-/issues/26698 and https://gitlab.kitware.com/cmake/cmake/-/issues/26613
Also see https://bugs.gentoo.org/951812 for bug occurring in Gentoo testing

**Comment by bkuhls** [comment]
Should be fixed by https://github.com/Pulse-Eight/platform/commit/d7faed1c696b1a6a67f114a63a0f4c085f0f9195

**Comment by opdenkamp** [comment]
@bkuhls is right — d7faed1c696b1a6a67f114a63a0f4c085f0f9195 fixed this. It raised `cmake_minimum_required` from `2.8.9` to `3.12.0` (and moved it above `project()`), which clears CMake 4's 3.5 floor. Thanks for tracking down the commit.

Verified both directions on **cmake 4.3.2**, rather than taking it on faith.

The tree as it was immediately before that commit still fails exactly as you reported:

```
CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
  Compatibility with CMake < 3.5 has been removed from CMake.
-- Configuring incomplete, errors occurred!     (exit 1)
```

Current `master` configures, builds and installs clean — exit 0 throughout, zero errors, zero deprecation warnings, zero dev warnings, and a working `libp8-platform.a`. `cmake_minimum_required(VERSION 3.12.0)` on line 1 is the only such call in the tree.

### But it is not in a release yet — that's the part that matters

**The fix is on `master` only.** The most recent tag, `p8-platform-2.1.0.1`, dates from **2016-10-26**; the fix landed **2025-02-25** and sits 37 commits past that tag. So anyone building from a release still hits this, which is presumably why Gentoo and Buildroot are carrying patches for it.

Closing this as completed since the defect itself is fixed, but the delivery problem is real and tracked in **#42**. If you're packaging from a tag and want to stay on one, `-DCMAKE_POLICY_VERSION_MINIMUM=3.5` configures the old tree anyway as a stopgap — though pointing at a `master` commit or carrying the one-line patch is cleaner.
